### ISSUE TITLE
Update support for OpenBSD's virtio 1.0 implementation (64-bit feature flagss)

### ISSUE THREAD

**Issue by voutilad** [voutilad/virtio_vmmci#3]
Looks to just have hit `-current`. Only change should be moving to 64-bit feature flags but need to keep an eye on CVS next few days.

For reference: 
https://github.com/openbsd/src/commit/750a9ae1d8d89a80cd59cfb15b30612d7bb130a1
https://github.com/openbsd/src/commit/b3dbd5f2ca08c6605873f66f80eb0045b3d69c0f

**Comment by voutilad** [comment]
This might be moot. Rebuilt and tested on my Ubuntu 18.04 vm and things seem fine. ¯\_(ツ)_/¯

**Comment by joe9** [comment]
@voutilad I upgraded to 6.5 and the clock sync does not seem to work anymore. The sysctl drift values are increasing but the sync is not happening anymore.
